config/routes.rb
Rails.application.routes.draw do

  root "pages#show", page: "home"

  resources :countries
  resources :visitors
  get "/pages/:page" => "pages#show", as: 'page'
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates_presence_of :name, :us_imports, :min_wage, :poverty, :country_image, :people_image
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  scope :recent, proc { order("created_at desc").limit(1) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to countries_path, notice: 'Country was successfully created.'
    else
      render :new
    end
  end

  def update
    if @country.update(country_params)
      redirect_to @country, notice: 'Country was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @country.destroy
    redirect_to countries_url, notice: 'Country was successfully deleted.'
  end

  private
    def set_country
      @country = Country.find(params[:id])
    end

    def country_params
      params.require(:country).permit(:name, :us_imports, :min_wage, :poverty, :people_image, :country_image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  def index
    @visitors_guess = Visitor.order(:guess).all
    @visitors_tshirt_made = Visitor.order(:tshirt_made).all
    @countries = Country.order(name: :desc).all
    @import_order_countries = Country.order(us_imports: :desc).all
  end

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(visitor_params)

    if @visitor.save
      redirect_to visitors_path, notice: 'Thank you for your answer.'
    else
      render :new
    end
  end

  def update
    if @visitor.update(visitor_params)
      redirect_to visitors_path, notice: 'Thank you for your answer.'
    else
      render :edit
    end
  end

  def destroy
    @visitor.destroy
    redirect_to visitors_url, notice: 'Visitor was successfully destroyed.'
  end

  private
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    def visitor_params
      params.require(:visitor).permit(:comment, :guess, :tshirt_made)
    end
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :us_imports %><br>
    <%= f.text_field :us_imports %>
  </div>
  <div class="field">
    <%= f.label :min_wage %><br>
    <%= f.text_field :min_wage %>
  </div>
  <div class="field">
    <%= f.label :poverty %><br>
    <%= f.text_field :poverty %>
  </div>
  <div class="field">
    <%= f.label :people_image %><br>
    <%= f.text_field :people_image %>
  </div>
  <div class="field">
    <%= f.label :country_image %><br>
    <%= f.text_field :country_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<center>
<h1>Let's start at the beginning.</h1><br>
  <%= image_tag "thread.png", size: '150x150'%>
  <br>
  <br>
<div class="dark-well">
  <div class="well well-lg 1">
    <h1>Where do you think your <%= image_tag "tshirt.png", size: '50x50' %> was made?</h1>
  </div>
</div>
<br>
<h2>Here's a clue:<br> More than 97% of apparel sold in the U.S.<br> is made overseas.</h2>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
<h2>2/3 of those imports comes from the Eastern Hemisphere.</h2>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
  <li></li>
<br>
<h1>Time to Take a Guess!</h1>
<div class= "guess">
  <%= image_tag "guess.png" %>
</div>
  <h2>Where do you think your T-shirt is from?</h2>
  <br>
  <br>
  <%= link_to 'GUESS', new_visitor_path, id: "add_visitor_answer_link", remote: true, class: "btn btn-lg btn-info" %>
  <br>
  <br>
  <br>
</center>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/new.js.erb
$('#new_country_link').hide().after('<%= j render("form") %>');

app/views/countries/show.html.erb
<center>
<h1>
  <%= @country.name %>
</h1>
<%= image_tag("#{@country.country_image}", size: '250x250') %>
<br>
<br>
  <div class="row">
    <div class="well well-lg col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h1>Imports / Exports</h1>
          <%= image_tag "export.png", size: '75x75'%>
          <h3><%= @country.name %> exports <span class="pop">$<%= @country.us_imports %></span> billion of apparel to the United States each year. This makes up <span class="pop"><%= number_to_percentage((((@country.us_imports)/81)*100), precision: 1) %> of total </span>US apparel imports.</h3>
      </div>
    </div>
  </div>
    <div class="well well-lg col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h1>Garment Worker Wages</h1>
          <%= image_tag "wages.png", size: '50x50'%>
          <h3>The <span class="pop">monthly</span> minimum wage for  <%= @country.name %>'s garment workers is equivalent to <span class="pop">$<%= @country.min_wage %> US</span>.</h3>
        </div>
      </div>
    </div>
    <div class="well well-lg col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h1>Poverty</h1>
          <%= image_tag "poverty.png", size: '100x100'%>
          <h3><span class="pop"><%= @country.poverty %>%</span> of <%= @country.name %>'s population lives on less than <span class="pop">$1.90 US</span>.</h3>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
          <p><%= link_to "Data Sources", page_path(:page=>'resources', :anchor => "data-sources") %></p>
  </div>
  <div class="row">
          <%= image_tag("#{@country.people_image}") %>
          <p><%= link_to "Image Sources", page_path(:page=>'resources', :anchor => "image-sources") %></p>
  </div>
  <h2><%= link_to "Explore more countries", visitors_path(:anchor => "countries-selection") %> | <%= link_to "See where your clothes end up", page_path(page: 'last_days') %></h2>
</center>
<br>
<br>
<br>

app/views/home/index.html.erb
<br>
<center>
<h2>Have you ever wondered where your T-Shirt came from?</h2>
<br>
<br>
<h3>Who made it? How far did it travel?</h3>
<br>
<div class= "spin">
  <%= image_tag "travel.png" %>
</div>
<br>
<h1>Come explore the <%= link_to "Journey of a T-shirt!", countries_path %></h1>
 <div class="click">
<h1><%= link_to countries_path do %>
<%= image_tag "tshirt.png" %>
<% end %>
</div>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journey of a T-Shirt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Slab:600' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
<div class="container">
  <%= yield %>
  <br>
    <%= yield :charts_js %>
  <strong><%= flash[:notice] %></strong>
  <br>
  <br>
  <footer class="site-footer">
    <h4><%= image_tag "planeL.png", size: '50x50' %> <%= link_to "Journey of a T-Shirt", root_path %> <%= image_tag "planeR.png", size: '50x50' %> --> <%= link_to "Take A Guess", countries_path %> --> <%= link_to "Explore A Country", visitors_path(:anchor => "#countries-selection") %> --> <%= link_to "Last Days", page_path(page: 'last_days') %> --> <%= link_to "Learn More/Resources", page_path(page: 'resources') %></h4>
    <%= yield(:footer) %>
  </footer>
</div
</body>
</html>

app/views/pages/home.html.erb
<br>
<center>
<h2>Have you ever wondered where your T-Shirt came from?</h2>
<br>
<br>
<h3>Who made it? How far did it travel?</h3>
<br>
<div class= "spin">
  <%= image_tag "travel.png" %>
</div>
<br>
<h1>Come explore the <%= link_to "Journey of a T-shirt!", countries_path %></h1>
 <div class="click">
  <%= link_to countries_path do %>
    <%= image_tag "tshirt.png" %>
  <% end %>
</div>
</center>

app/views/pages/last_days.html.erb
<center>
<h1>What Will Happen To Your <%= image_tag "tshirt.png", size: '100x100' %> </h1>
<h1>At The End of It's Journey?</h1>
<br>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<h2>On average, a person generates <span class="pop">82 lbs</span> of textile waste each year.</h2>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<div class="row">
  <div class="col-sm-6 col-md-5">
    <div class="dark-well">
      <div class="well well-lg">
      <h1><span class="pop">85%</span> (or 70 lbs) of a person's textiles will end up in the <br>
      <%= image_tag "trash.png", size: '100x100' %></h1>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-2">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </div>
  <div class="col-sm-6 col-md-5">
    <div class="dark-well">
      <div class="well well-lg">
      <h1>While <span class="pop">15%</span> (or 12 lbs) will be<br>
      donated or<br>
      <%= image_tag "recycle.png", size: '100x100' %></h1>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-md-5">
    <h4>Don't let your T-shirt end up in the trash! Find a place to <%= image_tag "recycle_symbol.png", size: "40x40" %><br> <a href="http://search.earth911.com/?what=t-shirt&where=Portland%2C+OR&list_filter=all&max_distance=25&family_id=&latitude=&longitude=&country=&province=&city=" target="_blank"> in Portland!</a></h4>
  </div>
  <div class="col-sm-6 col-md-2">
  </div>
  <div class="col-sm-6 col-md-5">
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-md-7">
  </div>
  <div class="col-sm-6 col-md-5">
    <h2>About <span class="pop">10%-20%</span> of donated clothing gets re-sold.</h2><br>
    <h2>Of the rest, depending on quality<br></h2>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <br>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-md-2">
    <div class="dark-well">
      <div class="well well-lg">
      <h3><span class="pop-extra">5%</span><br> will end up in the<br>
      <%= image_tag "trash.png", size: '75x75' %></h3>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-1">
  </div>
  <div class="col-sm-6 col-md-2">
    <div class="dark-well">
      <div class="well well-lg">
      <h3><span class="pop-extra">20%</span><br>will be recyled into fiber, mostly home insulation and carpet padding <br>
      <%= image_tag "padding.png", size: '75x75' %></h3>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-1">
  </div>
  <div class="col-sm-6 col-md-2">
    <div class="dark-well">
      <div class="well well-lg">
        <h3><span class="pop-extra">30%</span><br>will be recycled and coverted, mostly to industrial absorbants<br>
        <%= image_tag "absorbant.png", size: '75x75' %></h3>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-1">
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="dark-well">
      <div class="well well-lg">
        <h3><span class="pop-extra">45%</span><br>will be repurposed, mostly exported as second-hand clothing<br>
        <%= image_tag "clothes.png", size: '75x75' %></h3>
      </div>
    </div>
  </div>
</div>
<br>
<h2><%= link_to "Learn More/Resources", page_path(:page => "resources") %> | <%= link_to "Restart Your Journey", root_path %></h2>
</center>
<br>

app/views/pages/resources.html.erb
<center>
<bold><h1>Learn More</h1></bold>
</center>
<br>
<br>
<div class="row">
  <div class="col-md-8">
    <div class="well-single">
      <h2><div class= "pop", id="inspiration-for-site">Inspiration for this Site</div></h2>
    </div>
      <h3>Check out these resources for more information on the lifecycle of a T-Shirt</h3>
      <ul class="resources">
        <li><a href="http://truecostmovie.com/" target="_blank">The True Cost- Who Pays for the Price of Our Clothing?</a>
        <li><a href="http://apps.npr.org/tshirt/#/title" target="_blank">NPR's Planet Money Makes a T-Shirt</a>
        <li><a href="http://www.weardonaterecycle.org/index.html" target="_blank">Council for Textile Recycling</a>
        <li><a href="http://www.smartasn.org/" target="_blank">SMART - Secondary Materials and Recycled Textiles</a>
      </ul>
    </div>
  <div class="col-md-4">
    <center><%= image_tag "inspiration.png", size: "165x165" %></center>
  </div>
</div>
<br>
<br>
<div class="row">
  <div class="col-md-4">
    <center><%= image_tag "data.png" %></center>
  </div>
  <div class="col-md-8">
    <div class="well-single">
      <h2><div class= "pop", id="data-sources">Data Sources</div></h2>
    </div>
      <h3>All data in this site can be found at the following sources</h3>
      <h4>Data represent most current information available as of November 2015 unless otherwise specified.</h4>
      <ul class="resources">
        <li><a href="http://otexa.trade.gov/scripts/TQValue.exe/runquery?cat=1" target="_blank">U.S. Department of Commerce Office of Textiles and Apparel, August 2015</a>
        <li><a href="http://www.ilo.org/global/lang--en/index.htm" target="_blank">International Labor Organization</a>
        <li><a href="http://data.worldbank.org/indicator/SI.POV.DDAY" target="_blank">World Bank</a>
        <li><a href="http://justjobsnetwork.org/wp-content/pubs/reports/RealWageStudy.pdf" target="_blank">Center for American Progress</a>
        <li><a href="http://www.weardonaterecycle.org/index.html" target="_blank">Council for Textile Recycling</a>
        <li><a href="http://www.smartasn.org/" target="_blank">SMART - Secondary Materials and Recycled Textiles</a>
      </ul>
  </div>
</div>
<br>
<br>
<div class="row">
  <div class="col-md-8">
    <div class="well-single">
      <h2><div class= "pop", id="image-sources">Image Sources</div></h2>
    </div>
      <h3>Thank you to the following sources for their beautiful images</h3>
      <h4>International Labor Organization Asia and the Pacific</h4>
        <ul class="resources">
          <li><a href="https://www.flickr.com/photos/77173826@N08/7165858301/" target="_blank">Cambodia - (Better Factories Cambodia Project)</a>
          <li><a href="https://www.flickr.com/photos/iloasiapacific/10987405545/in/photostream/" target="_blank">Indonesia - (Better Work Indonesia)</a>
          <li><a href="https://www.flickr.com/photos/iloasiapacific/8249606304/in/album-72157630849383264/" target="_blank">Sri Lanka</a>
          <li><a href="https://www.flickr.com/photos/iloasiapacific/10987405545/in/photostream/" target="_blank">Vietnam - (Better Work Vietnam)</a>
        </ul>
      <h4>AFL-CIO America's Unions</h4>
        <ul class="resources">
          <li><a href="http://www.aflcio.org/content/download/147761/3770791/file/Honduras.PDF" target="_blank">Honduras</a>
        </ul>
      <h4>Individual Contributions</h4>
        <ul class="resources">
          <li><a href="https://www.flickr.com/photos/jajankie/5790840713/in/photolist-9PHzcg-b8q6Pe-bmGtAJ-2F4BRu-ntthJk-7JwZ8s-48pkNM-jFw8kQ-7QqbTh-9MsYiz-pfwtG6-99Z6V9-8oXtAX-8Ho5LB-8Ho7L2-bAHAhP-8Ho6Qr-8nNPUG-8nNPWW-8Hrgzj-8xECxK-8HrcGW-8LWNWQ-8HnWgM-8HnYcH-8Ho14F-8Ho27g-8HnX8n-8HnZ8P-f9X8At-J7ugV-jt7M2j-dmerFs-h1dqLs-rjX75S-9MvDBw-rZodaq-2EZ3ED-aABQzd-8o9VMu-atHioh-7UwjJi-4KdAoD-9ZKYAK-9ZKYCD-6oSxv8-3nxDek-2U93PW-9MvDBs-5tgnQX" target="_blank">Bangladesh</a>
          <li><a href="https://www.flickr.com/photos/blaineo/4643696151" target="_blank">China</a>
          <li><a href="http://news.psu.edu/photo/344138/2015/02/10/workers-rights" target="_blank">El Salvador</a>
          <li><a href="http://binaryapi.ap.org/ad9f8d07153f4e4f921727f8affdfb13/preview/AP320360479146.jpg?wm=api&ver=1" target="_blank">India</a>
          <li><a href="http://www.gettyimages.com/detail/news-photo/adding-the-special-details-to-jeans-in-irapuato-news-photo/141112362?license" target="_blank">Mexico</a>
        </ul>
  </div>
  <div class="col-md-4">
    <center><%= image_tag "camera.png", size:"150x150" %></center>
  </div>
</div>
<center>
  <div class= "spin">
    <%= image_tag "travel.png" %>
  </div>
  <h2><%= link_to "Restart Your Journey", root_path %></h2>
</center>
<br>
<br>
<br>

app/views/visitors/_form.html.erb
<%= form_for(@visitor) do |f| %>
  <% if @visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visitor.errors.count, "error") %> prohibited this guess from being saved:</h2>
      <ul>
      <% @visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3>
  <div class="field">
      <%= f.label :guess, "Where do you think your T-shirt was made?" %><br>
      <%= f.select :guess, ['China', 'Vietnam', 'Bangladesh', 'Indonesia', 'Mexico', 'India', 'Honduras', 'Cambodia', 'El Salvador', 'Sri Lanka', 'United States', 'Hand-Made', 'Other'] %>
  </div>
</h3><br>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li>
    <li></li><br>

    <h1>Check your tag <%= image_tag "tag.png", size: '50x50' %></h1><br>
    <h2>Did you guess correctly?</h2><br>
<h3>
  <div class="field">
      <%= f.label :tshirt_made, "Where was your T-shirt ACTUALLY made?"%><br>
      <%= f.select :tshirt_made, ['China', 'Vietnam', 'Bangladesh', 'Indonesia', 'Mexico', 'India', 'Honduras', 'Cambodia', 'El Salvador', 'Sri Lanka', 'United States', 'Hand-Made', 'Other'] %>
  </div><br>
  <div class="actions">
    <%= f.submit "Submit Answer", class: "btn btn-lg btn-info" %>
  </div>
</h3>
<% end %>

app/views/visitors/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form' %>

app/views/visitors/index.html.erb
<center>
<h1>Today's visitors have T-Shirts<br>
   from all over the world</h1>
<br>
<br>
<div class="row">
  <div class="col-md-6">
    <h1>Guesses Where T-shirts Where Made</h1>
    <%= pie_chart @visitors_guess.group(:guess).count, colors: ["#190000", "#660000", "#990000", "#cc0000", "#ff0000", "#ff3232", "#ff4c4c", "#ff6666", "#ff7f7f", "#ff9999", "#ffb2b2", "#ffcccc", "#ffe5e5"], library: {backgroundColor: "none"}%>
  </div>
  <div class="col-md-6">
    <h1>Where T-shirst Were <span class= "pop">Actually</span> Made</h1>
    <%= pie_chart @visitors_tshirt_made.group(:tshirt_made).count, colors: ["#190000", "#660000", "#990000", "#cc0000", "#ff3232", "#ff0000", "#ff4c4c", "#ff6666", "#ff7f7f", "#ff9999", "#ffb2b2", "#ffcccc", "#ffe5e5"], library: {backgroundColor: "none"} %>
  </div>
</div>
<br>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<br>
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>The US imports over <span class="pop">$80 Billion</span><br> of apparel EACH year.</h1>
    <%= image_tag "money.png", size: '100x100' %>
  </div>
  <div class="col-md-4">
  </div>
</div>
<br>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<br>
<div class="row">
  <div class="col-md-12">
    <h2>Top 10 Countries of Apparel Imports to US</h2>
    <h2>$US in Billions - 2014</h2>
  </div>
<div class="row">
  <div class="col-md-10">
    <div class= "map">
      <%= geo_chart @countries.group(:name).sum(:us_imports), colors: ["#ff9999", "#660000"], width: "1200px", height: "600px", library: {backgroundColor: "black"}%>
    </div>
  </div>
  <div class="col-md-2">
    <table class="table table-sm">
      <thead>
        <tr>
          <th><h4>Country</h4></th>
          <th><h4><strong>US$ Billion</h4></th>
        </tr>
      </thead>
      <tbody>
        <% @import_order_countries.each do |country| %>
          <tr>
            <td><%= link_to country.name, country_path(country) %></td>
            <td><center><div class="pop"><%= country.us_imports %></div><center></td>
            <!-- <td><%= link_to 'Edit', edit_country_path(country) %> |
                <%= link_to 'Destroy', country, method: :delete %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>
    <p><%= link_to "Source: U.S. Department of Commerce Office of Textiles and Apparel, August 2015", page_path(:page=>'resources', :anchor => "data-sources") %></p>
  </div>
</div>
<br>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<br>
<div class="dark-well">
  <div class="well well-lg", id="countries-selection">
    <h1>
      Was your T-shirt made in one of the TOP exporting countries?<br>
      <%= image_tag "binoculars.png", size: '150x150'%><br>
      Click to learn more about<br>
      the country and people!
    </h1>
      <br>
      <br>
    <div class="row">
      <div class="col-sm-1">
      </div>
      <% @import_order_countries.each do |country| %>
        <div class="col-sm-1">
          <%= link_to country.name, country_path(country) %><br>
          <%= image_tag("#{country.country_image}", size: '75x75') %>
        </div>
      <% end %>
      <div class="col-sm-1">
      </div>
    </div>
  </div>
</div>
</center>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form' %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/new.js.erb
$('#add_visitor_answer_link').hide().after('<%= j render("/visitors/form") %>');